
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND_KEY CAUSAL_KEY DEFINE_KEY DOMAIN_KEY EQUALS GOAL_KEY HINT_KEY HYPHEN LPAREN MODEL_KEY NAME NOT_KEY OR_KEY PARAMETERS_KEY PROBLEM_KEY RELATION_KEY RPAREN VARIABLEpddl : domain\n            | problemdomain : LPAREN DEFINE_KEY domain_def model_def_lst RPARENproblem : LPAREN DEFINE_KEY problem_def domain_def goal_def hint_def RPARENdomain_def : LPAREN DOMAIN_KEY NAME RPARENproblem_def : LPAREN PROBLEM_KEY NAME RPARENgoal_def : LPAREN GOAL_KEY LPAREN AND_KEY ground_predicates_lst RPAREN RPARENhint_def : LPAREN HINT_KEY NAME RPARENparameters_def : PARAMETERS_KEY LPAREN variables_lst RPAREN\n                      | PARAMETERS_KEY LPAREN RPARENmodel_def_lst : model_def model_def_lst\n                     | model_defmodel_def : LPAREN MODEL_KEY NAME parameters_def causal_def_lst RPARENcausal_def_lst : causal_def causal_def_lst\n                      | causal_defcausal_def : LPAREN CAUSAL_KEY NAME relation_def RPARENrelation_def : RELATION_KEY LPAREN AND_KEY literals_lst RPAREN\n                    | RELATION_KEY LPAREN OR_KEY literals_lst RPAREN\n                    | RELATION_KEY literalliterals_lst : literal literals_lst\n                    | literalliteral : LPAREN NOT_KEY predicate RPAREN\n               | predicateground_predicates_lst : ground_predicate ground_predicates_lst\n                             | ground_predicatepredicate : LPAREN NAME variables_lst RPAREN\n                 | LPAREN EQUALS VARIABLE VARIABLE RPAREN\n                 | LPAREN NAME RPARENground_predicate : LPAREN NAME constants_lst RPAREN\n                        | LPAREN NAME RPARENconstants_lst : constant constants_lst\n                     | constantvariables_lst : VARIABLE variables_lst\n                     | VARIABLEconstant : NAME'
    
_lr_action_items = {'LPAREN':([0,5,7,8,13,15,22,23,24,26,29,30,36,38,41,44,48,51,57,60,62,63,66,67,69,70,71,76,81,86,87,89,],[4,6,11,14,11,21,27,-5,-6,31,34,37,34,46,-13,-10,46,-9,64,-30,-7,-16,-23,-29,74,74,78,74,-28,-22,-26,-27,]),'$end':([1,2,3,19,33,],[0,-1,-2,-3,-4,]),'DEFINE_KEY':([4,],[5,]),'DOMAIN_KEY':([6,14,],[9,9,]),'PROBLEM_KEY':([6,],[10,]),'NAME':([9,10,18,32,40,46,53,58,61,64,74,78,],[16,17,25,39,50,53,58,-35,58,72,72,72,]),'MODEL_KEY':([11,],[18,]),'RPAREN':([12,13,16,17,20,28,35,36,37,39,41,42,43,45,47,48,49,52,53,54,55,56,58,59,60,61,63,65,66,67,68,72,75,76,77,79,80,81,83,84,85,86,87,88,89,],[19,-12,23,24,-11,33,41,-15,44,49,-13,-14,51,-34,54,-25,-8,-33,60,62,-24,63,-35,67,-30,-32,-16,-19,-23,-29,-31,81,83,-21,85,86,87,-28,-17,-20,-18,-22,-26,89,-27,]),'GOAL_KEY':([21,],[26,]),'PARAMETERS_KEY':([25,],[30,]),'HINT_KEY':([27,],[32,]),'AND_KEY':([31,64,],[38,69,]),'CAUSAL_KEY':([34,],[40,]),'VARIABLE':([37,45,72,73,82,],[45,45,45,82,88,]),'RELATION_KEY':([50,],[57,]),'OR_KEY':([64,],[70,]),'NOT_KEY':([64,74,],[71,71,]),'EQUALS':([64,74,78,],[73,73,73,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pddl':([0,],[1,]),'domain':([0,],[2,]),'problem':([0,],[3,]),'domain_def':([5,8,],[7,15,]),'problem_def':([5,],[8,]),'model_def_lst':([7,13,],[12,20,]),'model_def':([7,13,],[13,13,]),'goal_def':([15,],[22,]),'hint_def':([22,],[28,]),'parameters_def':([25,],[29,]),'causal_def_lst':([29,36,],[35,42,]),'causal_def':([29,36,],[36,36,]),'variables_lst':([37,45,72,],[43,52,80,]),'ground_predicates_lst':([38,48,],[47,55,]),'ground_predicate':([38,48,],[48,48,]),'relation_def':([50,],[56,]),'constants_lst':([53,61,],[59,68,]),'constant':([53,61,],[61,61,]),'literal':([57,69,70,76,],[65,76,76,76,]),'predicate':([57,69,70,71,76,],[66,66,66,79,66,]),'literals_lst':([69,70,76,],[75,77,84,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pddl","S'",1,None,None,None),
  ('pddl -> domain','pddl',1,'p_pddl','pddlparser.py',111),
  ('pddl -> problem','pddl',1,'p_pddl','pddlparser.py',112),
  ('domain -> LPAREN DEFINE_KEY domain_def model_def_lst RPAREN','domain',5,'p_domain','pddlparser.py',117),
  ('problem -> LPAREN DEFINE_KEY problem_def domain_def goal_def hint_def RPAREN','problem',7,'p_problem','pddlparser.py',122),
  ('domain_def -> LPAREN DOMAIN_KEY NAME RPAREN','domain_def',4,'p_domain_def','pddlparser.py',127),
  ('problem_def -> LPAREN PROBLEM_KEY NAME RPAREN','problem_def',4,'p_problem_def','pddlparser.py',133),
  ('goal_def -> LPAREN GOAL_KEY LPAREN AND_KEY ground_predicates_lst RPAREN RPAREN','goal_def',7,'p_goal_def','pddlparser.py',138),
  ('hint_def -> LPAREN HINT_KEY NAME RPAREN','hint_def',4,'p_hint_def','pddlparser.py',143),
  ('parameters_def -> PARAMETERS_KEY LPAREN variables_lst RPAREN','parameters_def',4,'p_parameters_def','pddlparser.py',149),
  ('parameters_def -> PARAMETERS_KEY LPAREN RPAREN','parameters_def',3,'p_parameters_def','pddlparser.py',150),
  ('model_def_lst -> model_def model_def_lst','model_def_lst',2,'p_model_def_lst','pddlparser.py',158),
  ('model_def_lst -> model_def','model_def_lst',1,'p_model_def_lst','pddlparser.py',159),
  ('model_def -> LPAREN MODEL_KEY NAME parameters_def causal_def_lst RPAREN','model_def',6,'p_model_def','pddlparser.py',166),
  ('causal_def_lst -> causal_def causal_def_lst','causal_def_lst',2,'p_causal_def_lst','pddlparser.py',170),
  ('causal_def_lst -> causal_def','causal_def_lst',1,'p_causal_def_lst','pddlparser.py',171),
  ('causal_def -> LPAREN CAUSAL_KEY NAME relation_def RPAREN','causal_def',5,'p_causal_def','pddlparser.py',178),
  ('relation_def -> RELATION_KEY LPAREN AND_KEY literals_lst RPAREN','relation_def',5,'p_relation_def','pddlparser.py',182),
  ('relation_def -> RELATION_KEY LPAREN OR_KEY literals_lst RPAREN','relation_def',5,'p_relation_def','pddlparser.py',183),
  ('relation_def -> RELATION_KEY literal','relation_def',2,'p_relation_def','pddlparser.py',184),
  ('literals_lst -> literal literals_lst','literals_lst',2,'p_literals_lst','pddlparser.py',194),
  ('literals_lst -> literal','literals_lst',1,'p_literals_lst','pddlparser.py',195),
  ('literal -> LPAREN NOT_KEY predicate RPAREN','literal',4,'p_literal','pddlparser.py',203),
  ('literal -> predicate','literal',1,'p_literal','pddlparser.py',204),
  ('ground_predicates_lst -> ground_predicate ground_predicates_lst','ground_predicates_lst',2,'p_ground_predicates_lst','pddlparser.py',212),
  ('ground_predicates_lst -> ground_predicate','ground_predicates_lst',1,'p_ground_predicates_lst','pddlparser.py',213),
  ('predicate -> LPAREN NAME variables_lst RPAREN','predicate',4,'p_predicate','pddlparser.py',221),
  ('predicate -> LPAREN EQUALS VARIABLE VARIABLE RPAREN','predicate',5,'p_predicate','pddlparser.py',222),
  ('predicate -> LPAREN NAME RPAREN','predicate',3,'p_predicate','pddlparser.py',223),
  ('ground_predicate -> LPAREN NAME constants_lst RPAREN','ground_predicate',4,'p_ground_predicate','pddlparser.py',233),
  ('ground_predicate -> LPAREN NAME RPAREN','ground_predicate',3,'p_ground_predicate','pddlparser.py',234),
  ('constants_lst -> constant constants_lst','constants_lst',2,'p_constants_lst','pddlparser.py',242),
  ('constants_lst -> constant','constants_lst',1,'p_constants_lst','pddlparser.py',243),
  ('variables_lst -> VARIABLE variables_lst','variables_lst',2,'p_variables_lst','pddlparser.py',251),
  ('variables_lst -> VARIABLE','variables_lst',1,'p_variables_lst','pddlparser.py',252),
  ('constant -> NAME','constant',1,'p_constant','pddlparser.py',260),
]
